# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [ ]:
tf.__version__

'2.8.2'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
# x is the set of independent variables and y is the dependent variable (output column - exited)
# first 3 columns are excluded as they *clearly* do not contribute to the final value
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [ ]:
# Label encoding used here for binary data
# need to assign indexes to categorical variables, i.e. denote each group by an index/numeric
# le is an instance of the LabelEncoder class
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[: ,2] = le.fit_transform(X[:, 2])

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [ ]:
# One Hot Encoding used as there is no order relationship between the geographical areas
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough') # The 1 here denotes column number
X = np.array(ct.fit_transform(X))

In [ ]:
# On performing One Hot Encoding, the dummy vaiables are moved to the first columns of the features matrix (first 3 columns here - eg: France here is 1.0 0.0 0.0)
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

### Feature Scaling

In [ ]:
# Feature Scaling is compulsory for Deep Learning, need to apply to *all* features here
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train) #Scale object is only fitted to training set to avoid information leakage
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
# create an object of a sequential class (a sequence of layers as opposed to a computational graph)
# Sequential class is from the Keras Library or Tensorflow 2.0 from the models module
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
# add is a method of the Sequential class
# To add a fully connected, simple layer : aim
# We enter in () a new instance of the Dense class for this layer
# Arguments  of Dense : 1. units or number of neurons in hidden layer, pick randomly and experiment (Hyperparameters : will *not* be trained, need to pick by trial and error)
# relu is the code for the Rectifier Function
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))


### Adding the second hidden layer

In [ ]:
# can change Hyperparameter values if required here
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### Adding the output layer

In [ ]:
# Dense class is used for fully connected layers
# units = 1 as dimension is 1 here (binary output, need only 1 dimension for encoding)
# Code for Sigmoid Function is 'sigmoid'
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
# choose an optimizer that can perform stochastic gradient descent
# loss function is C (cost function) : use binary_crossentropy for binary classification and categorical_crossentropy for non-binary classification (for this use SoftMax activation function in the output layer)
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [ ]:
# fit method is used for training
# batch training is the best for an ANN - classic value of size = 32 (Hyperparameter)
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5369 - accuracy: 0.7970
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4594 - accuracy: 0.8037
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4352 - accuracy: 0.8131
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4237 - accuracy: 0.8174
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4150 - accuracy: 0.8215
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4082 - accuracy: 0.8234
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4025 - accuracy: 0.8269
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3979 - accuracy: 0.8281
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3931 - accuracy: 0.8296
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3891 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

In [ ]:
# use predict method and enter the given information - 2D array is the input format
# Enter the values of the dummy variable (First 3 columns for country as they have been sent to the start on encoding)
# need to call predict method on observations with same scaling as training data
# During scaling : fitting would cause information leakage, only *transform* to be used on test data or new observations
# Threshold chosen here is 0.5
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [ ]:
# need to convert predicted probabilities into predicted binary outcomes : set threshold
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 0]]


### Making the Confusion Matrix

In [ ]:
# get accuracy value of ANN
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1522   63]
 [ 216  199]]


0.8605